sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yacaschdkr20/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yacaschdkr20/react-test npm test

after_success:
  - docker build -t yacaschdkr20/multi-client ./client
  - docker build -t yacaschdkr20/multi-nginx ./nginx
  - docker build -t yacaschdkr20/multi-server ./server
  - docker build -t yacaschdkr20/multi-worker ./worker
  # Log in to the docker CLI - to push image to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yacaschdkr20/multi-client
  - docker push yacaschdkr20/multi-nginx
  - docker push yacaschdkr20/multi-server
  - docker push yacaschdkr20/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-056837617387'
  bucket_path: 'docker-multi-deploy'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
